spring:
  application:
    name: titling-service

  datasource:
    username: ${database.postgres.username}
    password: ${database.postgres.password}
    url: ${database.postgres.url}

  flyway:
    enabled: true
    schemas: public
    locations: classpath:/db/migration, classpath:/db/postgres
    baseline-on-migrate: true
    user: flyway_migrate

  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    info:
      enabled: true
    flyway:
      enabled: true
    env:
      enabled: true

logging:
  level:
    org.springframework.security.web.access: WARN
    com.zaxxer.hikari: WARN
    com.myyesgo: INFO
    org.springframework:.vault: DEBUG

external:
  apiBaseUrl: http://localhost:7000
  isEmailEnabled: ${env.emailFeature.enabled}

server:
  port: 9001